DECLARE
	TOTAL INT;
BEGIN
	UPDATE STUDENT SET smark = smark + 5;

	IF SQL%NOTFOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO STUDENT SELECTED/UPDATED');

	ELSIF SQL%FOUND THEN
		TOTAL := SQL%ROWCOUNT;
		DBMS_OUTPUT.PUT_LINE(TOTAL || ' STUDENTS RECORD UPDATED');
	END IF;
END;
/