-- PROGRAM FOR EXCEPTION RAISED, INCLUDES BOTH USER DEFINE AND SYSTEM DEFINE EXCEPTIONS
DECLARE
	ID STUDENT.SID % TYPE;
	NAME STUDENT.SNAME % TYPE;
	CITY STUDENT.SCITY % TYPE;
	MARK STUDENT.SMARK % TYPE;
	INVALID EXCEPTION;
BEGIN
	ID := &SID;
	NAME := &SNAME;
	CITY := &SCITY;
	MARK := &SMARK;

	IF MARK > 100 THEN
		RAISE INVALID;
	END IF;

	INSERT INTO STUDENT VALUES(ID,NAME,CITY,MARK);

EXCEPTION
	WHEN INVALID THEN
		DBMS_OUTPUT.PUT_LINE('MARKS CANNOT BE GREATER THEN 100... PLEASE RE-CHECK THE MARKS ENTERED.');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR!');
END;
/