DECLARE 
	A INT := 0;
	B INT := 1;
	TEMP INT;
	N INT;
	I INT;
BEGIN
	N := &N;
	DBMS_OUTPUT.PUT_LINE('FIBONACCI SERIES GENERATED IS:');
	DBMS_OUTPUT.PUT_LINE(A);
	DBMS_OUTPUT.PUT_LINE(B);

	FOR I IN 1..N
	LOOP
		TEMP := A + B;
		DBMS_OUTPUT.PUT_LINE(TEMP);
		A := B;
		B := TEMP;
	END LOOP; 
END;
/