DECLARE
	NUM INT;
BEGIN

	NUM := &NUM;

	IF MOD(NUM,2) = 0 THEN
		DBMS_OUTPUT.PUT_LINE('THE NUMBER ' || NUM || ' IS EVEN');
	ELSE
 		DBMS_OUTPUT.PUT_LINE('THE NUMBER ' || NUM || ' IS ODD');
	END IF;
END;
/